### ISSUE TITLE
StackOverFlowError

### ISSUE THREAD

**Issue by FuelBarrel881** [great-big-world/great-big-world#17]
I keep getting 'The game crashed whilst exception in server tick loop
Error: java.lang.StackOverflowError: Exception in server tick loop' along with 'exit code: minus 1'

**Comment by jack-zisa** [comment]
I'm going to need more information in order to fix this. Can you send me the log (in .minecraft/logs) of when you ran the game? If not, I'm going to need more context about other mods used, what you were doing when it crashed, version of the mod etc. This would all be provided in the log if you can provide that.
