### ISSUE TITLE
Dried Bamboo Implementation

### ISSUE THREAD

**Issue by ereese99** [great-big-world/great-big-world#5]
Hey, it won't let me comment on CurseForge on the Dried Bamboo mod, but do you have any plans on merging it into this mod? Huge fan of it, the standalone version causes crashes with Paradise Lost for some reason (their mod is kinda broken to be fair), and I figured if it was merged here it wouldn't do that. Thanks!

**Comment by jack-zisa** [comment]
Paradise Lost breaks a lot of mods. For some reason they feel the need to find hacky solutions to a lot of different things that shouldn't be difficult to implement. It's very unfortunate because the mod looks great!

As for Dried Bamboo, I'm most likely not going to be adding it to Great Big World. This is because of:
1. 1.20 is adding it
2. I don't really see the need for it since they're still available for 1.19.2 & 1.19.3. The Paradise Lost issue is almost certainly caused on their end.
